name: 🚀 Despliegue SFTP a IONOS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener código
        uses: actions/checkout@v4

      - name: 📤 Subir por SFTP
        uses: appleboy/scp-action@v0.1.7 # <--- Esta es la herramienta correcta
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "." # Coge todos los archivos de tu GitHub
          target: "SantiPiso" # <--- Apunta a la carpeta que ya existe DENTRO de SantiGil
          strip_components: 0
