name: 🚀 Despliegue SFTP a IONOS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener código
        uses: actions/checkout@v4

      - name: 📤 Subir por SFTP
        uses: appleboy/sftp-action@v0.1.8
        with:
          host: ${{ secrets.FTP_SERVER }}      # home450938841.1and1-data.host
          username: ${{ secrets.FTP_USERNAME }} # acc2059079233
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "./"
          target: "/kunden/homepages/20/d450938841/htdocs/SantiGil/"
